apiVersion: apps/v1
kind: Deployment
metadata:
  name: authapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authapi
  template:
    metadata:
      labels:
        app: authapi
    spec:
      containers:
      - name: authapi
        image: despossivel/authapi:TAG
        ports:
        - containerPort: 3008
      imagePullSecrets:
      - name: regcred
      