# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: postgres-volume-claim
#   labels:
#     app: postgres
# spec:
#   # storageClassName: ams-eca8bf8ec11c4e

#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 40Gi
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-volume-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 15Gi
  storageClassName: vultr-block-storage
