apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume
spec:
  capacity:
    storage: 40Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: vultr-block-storage
  csi:
    driver: block.csi.vultr.com
    volumeHandle: fra-a1fd78fe572242

