apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloak-themes-custom
spec:
  capacity:
    storage: 40Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: auto
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /Users/matheus.brito/Documents/lab/MVP/fc2-micro-auth/.k8s/keycloak/keycloakify-starter/build_keycloak/src/main/resources/theme/keycloakify-starter
