name: Build, Publish, and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-publish-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"

      - name: Criar arquivo .env
        run: |
          touch .env
          echo "NODE_ENV=${{ vars.NODE_ENV }}" > .env
          echo "PORT=${{ vars.PORT }}" >> .env
          echo "REALM_ADMIN=${{ vars.REALM_ADMIN }}" >> .env
          echo "REALM=${{ vars.REALM }}" >> .env
          echo "ADMIN_USER=${{ secrets.ADMIN_USER }}" >> .env
          echo "ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }}" >> .env
          echo "OIDC_RESOURCE=${{ vars.OIDC_RESOURCE }}" >> .env
          echo "OIDC_AUTH_SERVER_URL=${{ vars.OIDC_AUTH_SERVER_URL }}" >> .env
          echo "OIDC_REALM=${{ vars.OIDC_REALM }}" >> .env
          echo "OIDC_SECRET=${{ secrets.OIDC_SECRET }}" >> .env
 
      # - name: Build and push Docker image
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     push: true
      #     tags: despossivel/authapi:${{ steps.slug.outputs.sha8 }}

      # - name: Replace image tag in deployment.yml
      #   run: sed -i 's|authapi:TAG|authapi:${{ steps.slug.outputs.sha8 }}|g' ./.k8s/deployment.yml

      # - name: Set up kubectl
      #   uses: azure/k8s-set-context@v1
      #   with:
      #     method: kubeconfig
      #     kubeconfig: ${{ secrets.KUBECONFIG }}

      # - name: Set up Kubernetes context
      #   uses: Azure/k8s-set-context@v1
      #   with:
      #     kubeconfig: ${{ secrets.KUBECONFIG }}

      # - name: Deploy to Kubernetes
      #   run: |
      #     kubectl apply -f ./.k8s/deployment.yml
      #     kubectl apply -f ./.k8s/service.yml
